# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run test:ci
  displayName: 'npm install and build'

- task: PublishTestResults@1
  inputs:
    testRunner: JUnit
    testResultsFiles: ./junit.xml
  displayName: 'Publish Test Results'

- script: |
    docker build -t $(dockerId).azurecr.io/$(system.teamProject) .
    docker login -u $(acr-service-principal-id) -p $(acr-service-principal-password) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(system.teamProject)
  displayName: 'Build Docker image and publish on ACR'
