apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: teamwork
  name: teamwork
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: teamwork
    spec:
      containers:
      - image: neoscontainerregistry.azurecr.io/teamwork:latest
        name: teamwork
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
